language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN='1873a52f-5df6-418c-96fc-bf38121fdec6'

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - kosas@mail.ru
    on_success: never # default: change
    on_failure: always # default: always